[2025-06-25T18:06:21.467+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline.s3_upload manual__2025-06-25T18:06:16.470477+00:00 [queued]>
[2025-06-25T18:06:21.473+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline.s3_upload manual__2025-06-25T18:06:16.470477+00:00 [queued]>
[2025-06-25T18:06:21.473+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-06-25T18:06:21.479+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): s3_upload> on 2025-06-25 18:06:16.470477+00:00
[2025-06-25T18:06:21.484+0000] {standard_task_runner.py:57} INFO - Started process 186 to run task
[2025-06-25T18:06:21.487+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_reddit_pipeline', 's3_upload', 'manual__2025-06-25T18:06:16.470477+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/reddit_dag.py', '--cfg-path', '/tmp/tmpcxuljbut']
[2025-06-25T18:06:21.489+0000] {standard_task_runner.py:85} INFO - Job 36: Subtask s3_upload
[2025-06-25T18:06:21.523+0000] {task_command.py:416} INFO - Running <TaskInstance: etl_reddit_pipeline.s3_upload manual__2025-06-25T18:06:16.470477+00:00 [running]> on host f892d2298fb9
[2025-06-25T18:06:21.568+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Paresh Jadhav' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline' AIRFLOW_CTX_TASK_ID='s3_upload' AIRFLOW_CTX_EXECUTION_DATE='2025-06-25T18:06:16.470477+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-25T18:06:16.470477+00:00'
[2025-06-25T18:06:21.578+0000] {aws_etl.py:14} ERROR - module 's3fs' has no attribute 's3FileSystem'
[2025-06-25T18:06:21.578+0000] {aws_etl.py:25} ERROR - 'NoneType' object has no attribute 'exists'
[2025-06-25T18:06:21.579+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/aws_s3_pipline.py", line 9, in upload_s3_pipeline
    upload_to_s3(s3,file_path,AWS_BUCKET_NAME,file_path.split("/")[-1])
AttributeError: 'NoneType' object has no attribute 'split'
[2025-06-25T18:06:21.587+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=etl_reddit_pipeline, task_id=s3_upload, execution_date=20250625T180616, start_date=20250625T180621, end_date=20250625T180621
[2025-06-25T18:06:21.593+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 36 for task s3_upload ('NoneType' object has no attribute 'split'; 186)
[2025-06-25T18:06:21.619+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-06-25T18:06:21.632+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
