[2025-06-24T10:23:16.515+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2025-06-24T10:23:14.871944+00:00 [queued]>
[2025-06-24T10:23:16.520+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2025-06-24T10:23:14.871944+00:00 [queued]>
[2025-06-24T10:23:16.521+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-06-24T10:23:16.527+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): reddit_extraction> on 2025-06-24 10:23:14.871944+00:00
[2025-06-24T10:23:16.532+0000] {standard_task_runner.py:57} INFO - Started process 44 to run task
[2025-06-24T10:23:16.536+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_reddit_pipeline', 'reddit_extraction', 'manual__2025-06-24T10:23:14.871944+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/reddit_dag.py', '--cfg-path', '/tmp/tmp99fhdap1']
[2025-06-24T10:23:16.537+0000] {standard_task_runner.py:85} INFO - Job 6: Subtask reddit_extraction
[2025-06-24T10:23:16.578+0000] {task_command.py:416} INFO - Running <TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2025-06-24T10:23:14.871944+00:00 [running]> on host f892d2298fb9
[2025-06-24T10:23:16.636+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Paresh Jadhav' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline' AIRFLOW_CTX_TASK_ID='reddit_extraction' AIRFLOW_CTX_EXECUTION_DATE='2025-06-24T10:23:14.871944+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-24T10:23:14.871944+00:00'
[2025-06-24T10:23:16.637+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: reddit_pipeline() missing 1 required positional argument: 'filename'
[2025-06-24T10:23:16.648+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=etl_reddit_pipeline, task_id=reddit_extraction, execution_date=20250624T102314, start_date=20250624T102316, end_date=20250624T102316
[2025-06-24T10:23:16.657+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 6 for task reddit_extraction (reddit_pipeline() missing 1 required positional argument: 'filename'; 44)
[2025-06-24T10:23:16.669+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-06-24T10:23:16.682+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
